spring.datasource.url=jdbc:mysql://localhost/adopet?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

#Não enviar stackTrace pela rede
server.error.include-stacktrace=never