spring.application.name=screenmusic

spring.datasource.url=jdbc:postgresql://localhost:5433/screenmusic
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
